[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ['nodejs-14_x', 'npm-8_x']

[phases.install]
cmds = ['npm install --no-package-lock', 'cd client && npm install --no-package-lock']

[phases.build]
cmds = ['cd client && npm run build']

[start]
cmd = 'npm start'